/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author lab01
 */
import br.aeso.exercicio.fachada.Fachada;
import br.aeso.exercicio.fornecedor.Fornecedor;
import br.aeso.exercicio.cliente.Cliente;
import br.aeso.exercicio.cliente.ClienteNaoExncontradoException;
import br.aeso.exercicio.notaFiscal.NotaFiscal;
import br.aeso.exercicio.notaFiscal.NotaFiscalJaCadastradaException;
import br.aeso.exercicio.notaFiscal.NotaFiscalNaoEncontradaException;
import br.aeso.exercicio.pedido.Pedido;
import br.aeso.exercicio.pedido.PedidoNaoEncontradoException;
import br.aeso.exercicio.util.ComboItem;
import br.aeso.exercicio.vendedor.VendedorNaoEncontradoException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
public class FormularioNotaFiscal extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioNotaFiscal
     */
    public FormularioNotaFiscal() {
        initComponents();
        this.carregarPedidos();
    }
    
    public FormularioNotaFiscal(NotaFiscal NotaFiscal) {
        initComponents();
        this.carregarPedidos();
        if(NotaFiscal == null){
            System.out.println("NotaFiscal Vasio on FormAtualizar!!!");
            return;
        }
        this.codigo = NotaFiscal.getCodigo();
        this.emitente.setText(NotaFiscal.getEmitente());
        DefaultComboBoxModel modelPedido = (DefaultComboBoxModel) this.pedido.getModel();
        for(int i = 0; i < modelPedido.getSize(); i++){
            ComboItem combo = (ComboItem) modelPedido.getElementAt(i);
            if(combo.getValue() == NotaFiscal.getPedido().getCodigo()){
                this.pedido.setSelectedIndex(i);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCPF = new javax.swing.JLabel();
        emitente = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        Erros = new javax.swing.JLabel();
        Atualizar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pedido = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario Cliente");
        setPreferredSize(new java.awt.Dimension(880, 500));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        lbCPF.setText("Emitente");

        emitente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emitenteFocusGained(evt);
            }
        });
        emitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emitenteActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Pedido");

        pedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCPF)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emitente)
                            .addComponent(pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Erros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(240, 240, 240))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(Atualizar)
                    .addComponent(btnCadastrar))
                .addGap(50, 50, 50)
                .addComponent(Erros, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addGap(144, 144, 144))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emitenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emitenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emitenteActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnCadastrarActionPerformed
    private void carregarPedidos(){
        Fachada fachada = new Fachada();
        
        try {
            this.pedidos = fachada.listarPedido();
            int i = 0;
            DefaultComboBoxModel model = (DefaultComboBoxModel) this.pedido.getModel();
            model.removeAllElements();
            ComboItem[] item;
            item = new ComboItem[this.pedidos.size()];
            for(Pedido pedido : this.pedidos){
               String strItem = pedido.getCodigo() + " - " + pedido.getCliente().getNome();
               ComboItem combo = new ComboItem();
               combo.setLabel(strItem);
               combo.setValue(pedido.getCodigo());
               model.addElement(combo);
               i++;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClienteNaoExncontradoException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (VendedorNaoEncontradoException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        }          
    }
    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        // TODO add your handling code here:
        boolean resposta = this.validar();
        if(resposta == false){
            Erros.setText("");
            Erros.setText("Campo(s) obrigatorio(s) mal preenchido!!!");
            Erros.setVisible(true);
            
        }
        String emitente = this.emitente.getText();
        ComboItem itemPedido = (ComboItem) this.pedido.getSelectedItem();
        int codigoPedido = itemPedido.getValue();
        Pedido pedido = this.getPedido(codigoPedido);
        if(pedido == null){
            Erros.setText("Fornecedor Invalido!!!");
            Erros.setVisible(true);
            return;
        }
        Date data = new Date(); 
        NotaFiscal NotaFiscal = new NotaFiscal(1, emitente, pedido, data);
        Fachada fachada = new Fachada();
        try {
            fachada.cadastrarNotaFiscal(NotaFiscal);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotaFiscalJaCadastradaException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotaFiscalNaoEncontradaException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PedidoNaoEncontradoException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarMouseClicked
    private Pedido getPedido(int codigo){
        for(Pedido pedido : this.pedidos){
            if(codigo == pedido.getCodigo()){
                return pedido;
            }
        }
        return null;
    }
    private void emitenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emitenteFocusGained
        // TODO add your handling code here:
        Erros.setVisible(false);
    }//GEN-LAST:event_emitenteFocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        Erros.setVisible(false);
    }//GEN-LAST:event_formFocusGained

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        boolean resposta = this.validar();
        if(resposta == false){
            Erros.setText("");
            Erros.setText("Campo(s) obrigatorio(s) mal preenchido!!!");
            Erros.setVisible(true);
            
        }
        String emitente = this.emitente.getText();
        ComboItem itemPedido = (ComboItem) this.pedido.getSelectedItem();
        int codigoPedido = itemPedido.getValue();
        Pedido pedido = this.getPedido(codigoPedido);
        if(pedido == null){
            Erros.setText("Fornecedor Invalido!!!");
            Erros.setVisible(true);
            return;
        }
        Date data = new Date();
        NotaFiscal NotaFiscal = new NotaFiscal(this.codigo, emitente, pedido, data);
        System.out.println(NotaFiscal.getCodigo());
        Fachada fachada = new Fachada();
        try {
            fachada.atualizarNotaFiscal(NotaFiscal);
        } catch (NotaFiscalJaCadastradaException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormularioNotaFiscal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AtualizarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed
    private boolean validar(){
        String[] valores = new String[]{this.emitente.getText()};
        for(String valor : valores){
            if(this.validarTexto(valor) == false){
                return false;
            }
        }
        return true;
    }
    
    private boolean validarTexto(String valor){
        if(valor.isEmpty()){
            return false;
        }
        
        if(valor.trim().equals("")){
            return false;
        }
        
        String[] valores = new String[]{"*", "_", "'", "=", "+", "§", "{", "}", "[", "]", "?", ":", ";", "?", "|", "\\", "/", ","};
        int correta = 0;
        
        for(String caractere : valores){
            if(valor.indexOf(caractere) != -1){
                return false;
            }
            if(this.quantOcorrencia(caractere, valor) == valor.length()){
                return false;
            }
        } 
        return true;
    }
    
    private int quantOcorrencia(String needle, String stack){
        String[] valores = stack.split("");
        int quantOcorrencias = 0;
        for(String valor : valores){
           if(valor.equals(needle)){
               quantOcorrencias++;
           }
        }
        return quantOcorrencias;
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioNotaFiscal().setVisible(true);
            }
        });
    }
    private int codigo;
    private ArrayList<Pedido> pedidos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JLabel Erros;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField emitente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JComboBox<String> pedido;
    // End of variables declaration//GEN-END:variables
}
